@ECHO OFF
REM TASM automatic assembler

REM Set the path to your TASM installation here
SET TOOLPATH=E:\TASM


ECHO Assembling VIGENERE.ASM ...
%TOOLPATH%\TASM.EXE VIGENERE.ASM
IF ERRORLEVEL 1 GOTO ASMFAIL

ECHO.
ECHO Linking VIGENERE.OBJ ...
%TOOLPATH%\TLINK.EXE VIGENERE.OBJ
IF ERRORLEVEL 1 GOTO LINKFAIL
GOTO _LINK_DONE


:_LINK_DONE
ECHO.
ECHO Build successful!
DEL VIGENERE.MAP
DEL VIGENERE.OBJ
GOTO END


:ASMFAIL
ECHO Assembly failed!
GOTO END

:LINKFAIL
ECHO Linking failed!
GOTO END

:END